### ISSUE TITLE
Friends Episodes

### ISSUE THREAD

**Issue by TiesToetToet** [dheerajrp/dheerajrp#1]
Deer Dheerajrp,

May i ask why the repository where you could download all the Friends episodes is gone. The link still exists: https://github.com/dheerajrp/Download-FRIENDS-all-seasons , but it brings me to a 404. I kindly ask you to bring it back or maybe you could send the files to me.

Your sincerely
TiesToetToet

**Comment by dheerajrp** [comment]
Hi TiesToetToet

I have made the repo private. Because I am using an entry url in the code which is not working now. It gives some other results. This is the url - https://s8.bitdl.ir/Series/friends
The code works only if this url works. I am searching for alternatives. 
I have made the repository public for your reference.
